import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import TanStackProvider from "../components/TanStackProvider/TanStackProvider";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "500", "700"], // какие начертания нужны
  subsets: ["latin", "cyrillic"], // можно оставить только "latin", если кириллица не нужна
  display: "swap",               // чтобы не было задержки при загрузке
  variable: "--font-roboto",     // создаст CSS-переменную для использования
});


export const metadata: Metadata = {
  title: "Create Note",
  description: "NoteHub - your personal note-taking app",
  openGraph : {
    title: 'Create Next App',
    description: 'Generated by create next app',
    url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
    images: [
      {
        url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
        width: 1200,
        height: 630,
        alt: 'NoteHub',
      },
    ],
  },
};

export default function RootLayout({children, modal}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <TanStackProvider>
          <Header />
          <main>
            {children}
            {modal}
          </main>
         <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
