import type { Metadata } from "next";

import NoteForm from "../../../../components/NoteForm/NoteForm";
import css from "./CreateNote.module.css";

export const metadata: Metadata = {
  title: "Create Note",
  description: "NoteHub - your personal note-taking app",
  openGraph : {
    title: 'NoteHub - Page Not Found',
    description: 'Generated by create note',
    url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
    images: [
      {
        url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
        width: 1200,
        height: 630,
        alt: 'NoteHub',
      },
    ],
  },
};



function CreateNotePage() {

  return  (
<main className={css.main}>
  <div className={css.container}>
    <h1 className={css.title}>Create note</h1>
	   <NoteForm />
  </div>
</main>
  );

}
export default CreateNotePage;
